### ISSUE TITLE
Still cannot assign an issue to Rebecca even though she says she has read/write access

### ISSUE THREAD

**Issue by amitvakula** [HarpGrantProgram/HarpGrantProgram.github.io#5]

**Comment by rmartin95** [comment]
![github issue creation](https://cloud.githubusercontent.com/assets/12525185/7905086/cd213040-07c6-11e5-9e4a-ed865c0cd805.png)

**Comment by mmussomele** [comment]
fixed

**Comment by amitvakula** [comment]
awesome thanks Matt! how were you able to assign her?

**Comment by mmussomele** [comment]
She was only added to the org, I added her to the repo team
